/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CasoRouteImport } from './routes/caso'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as ReservarRouteImport } from './routes/reservar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasoRoute = CasoRouteImport.update({
  id: '/caso',
  path: '/caso',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarRoute = ReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/caso': typeof CasoRoute
  '/panel': typeof PanelRoute
  '/reservar': typeof ReservarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/caso': typeof CasoRoute
  '/panel': typeof PanelRoute
  '/reservar': typeof ReservarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/caso': typeof CasoRoute
  '/panel': typeof PanelRoute
  '/reservar': typeof ReservarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/caso' | '/panel' | '/reservar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/caso' | '/panel' | '/reservar'
  id: '__root__' | '/' | '/caso' | '/panel' | '/reservar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasoRoute: typeof CasoRoute
  PanelRoute: typeof PanelRoute
  ReservarRoute: typeof ReservarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caso': {
      id: '/caso'
      path: '/caso'
      fullPath: '/caso'
      preLoaderRoute: typeof CasoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar': {
      id: '/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof ReservarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasoRoute: CasoRoute,
  PanelRoute: PanelRoute,
  ReservarRoute: ReservarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
